language: python

os:
- linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

python:
- "2.7"

install:
- sudo python setup.py install
- pip install codecov

before_script: 
- LD_LIBRARY_PATH=`pwd`/libs/linux64
- export LD_LIBRARY_PATH

script:
# - python -m unittest discover -s test
- coverage run --source intrepid test/test_bmc.py

after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
