language: python

os: 
- linux

python:
- "2.7"
- "3.5"
- "3.5-dev" # 3.5 development branch
- "nightly" # currently points to 3.6-dev

before_script:
- cp libs/linux64/* intrepid
- sudo apt-get install swig

script: 
- python -m unittest discover -s test
