language: python

os:
    - linux

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-5
        - g++-5

python:
    - "2.7"

install:
    - pip install coverage
    - pip install coveralls
    - python setup.py install

before_script: 
    - export LD_LIBRARY_PATH=`pwd`/libs/linux64

script:
    - echo 'done'
#    - coverage run -m unittest discover
#    - python -m unittest discover

#after_success:
#    - coverage report
#    - coveralls
