sudo: required
dist: trusty

language: python

os: linux

python:
- "2.7"

before_script: 
- sudo python setup_linux64.py install
- LD_LIBRARY_PATH=`pwd`/libs/linux64
- export LD_LIBRARY_PATH
- sudo apt-get install libstdc++6

script: python -m unittest discover -s test
