language: python

os: linux

python:
- "2.7"
- "3.5"

before_script: 
- echo $LD_LIBRARY_PATH
- LD_LIBRARY_PATH=$LD_LIBRARY_PATH:libs/linux64
- export LD_LIBRARY_PATH
- echo $LD_LIBRARY_PATH

script: python -m unittest discover -s test
