language: python

os:
    - linux

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-4.8
        - g++-4.8

python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install

before_script: 
    - export LD_LIBRARY_PATH=`pwd`/libs/linux64

script:
    - coverage -m unittest discover
    - coverage report
    - coveralls
