language: python

os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

python:
- "2.7"

before_script: 
- sudo python setup_linux64.py install
- LD_LIBRARY_PATH=`pwd`/libs/linux64
- export LD_LIBRARY_PATH
- g++ -v

script: python -m unittest discover -s test
